### PR TITLE
added include that it works with latest opencv on ubuntu 20.04

### PR DESCRIPTION
**Pull request by LaneaLucy**
tried to compile under Ubuntu 20.04 with latest libopencv-dev python3-opencv at time (20.03.2023)

got error: ‘Rodrigues’ is not a member of ‘cv’

Fix: add #include <opencv2/calib3d.hpp> in node.cpp

### CODE REVIEW

**Comment by anbello** [comment]
Thanks :)
